le_comfort_products_list = [
    "Aaron",
    "Abbraccio",
    "Abbraccio Light",
    "Abby",
    "Academy",
    "Adda",
    "Adela",
    "Air",
    "Alessandra",
    "Allen",
    "Amy",
    "Andy",
    "Anita",
    "Apollo",
    "Argo",
    "Aspen",
    "Astor",
    "Atrium",
    "Aurora",
    "Bacio",
    "Bacio Light",
    "Bali",
    "Bambusa",
    "Bangkok",
    "Barbados",
    "Bellargo",
    "Belmondo",
    "Boon",
    "Bowie",
    "Bowie Light",
    "Break",
    "Britney",
    "Byron",
    "Caligo",
    "Calvin",
    "Camomilla",
    "Caravaggio",
    "Caroline",
    "Cassandra",
    "Catlin",
    "Celine",
    "Christopher",
    "Club",
    "Collins",
    "Cortina",
    "Cupido",
    "Dafne",
    "Dama",
    "Dodo",
    "Donovan",
    "Duo",
    "Egon",
    "Eline",
    "Elodie",
    "Emmet",
    "Essential",
    "Estate",
    "Fenice",
    "Fold",
    "Forest",
    "Fris",
    "Galen",
    "Gareth",
    "Gaucho",
    "Gelsomino",
    "Gillan",
    "Graffiti",
    "Greta",
    "Ground",
    "Guapa",
    "Guscio",
    "Harvey",
    "Hesperis",
    "Hollis",
    "Horizon",
    "Houston",
    "Houston Light",
    "Icaro",
    "Illy",
    "Inside",
    "Ipanema",
    "Isabel",
    "Ischia",
    "Jaro",
    "Joplin",
    "Kallima",
    "Kennedy",
    "King",
    "Klizia",
    "Kubik",
    "Lala",
    "Lambert",
    "Lantana",
    "Leslie",
    "Logan",
    "Lola",
    "Lord",
    "Love",
    "Luis",
    "Madeira",
    "Magyster",
    "Maldive",
    "Meggy",
    "Metropolitan",
    "Mike",
    "Mimas",
    "Mirabilis",
    "Moby",
    "Monaco",
    "Monet",
    "Naxos",
    "Nicole",
    "Nixon",
    "Norton",
    "Opera",
    "Oyster",
    "Papilio",
    "Pasodoble",
    "Pentas",
    "Pervinca",
    "Phlox",
    "Pieris",
    "Plaris",
    "Plumeria",
    "Pontia",
    "Primrose",
    "Prince",
    "Privè",
    "Queen",
    "Raffaello",
    "Ralph",
    "Reed",
    "Reed Light",
    "Renoir",
    "Robert",
    "Rosa",
    "Russel",
    "Santorini",
    "Sebastian",
    "Sfinge",
    "Shelley",
    "Silene",
    "Simba",
    "Snap",
    "Solanum",
    "Sommier",
    "Spencer",
    "Tahiti",
    "Tania",
    "Tecla",
    "Tender",
    "Thoas",
    "Tidy",
    "Tile",
    "Timis",
    "Timoty",
    "Tina",
    "Together",
    "Tower",
    "Trick",
    "Vanessa",
    "Vasco",
    "Viky",
    "Vincent",
    "Voyage",
    "Wall",
    "Wheel",
    "Windsor",
    "Wrap",
    "Zeno",
]

le_comfort_coverings_list = [
    "Beauty",
    "Betsy",
    "Bonnie",
    "Brez",
    "Bride",
    "Cannes",
    "Cao",
    "Cento",
    "Cereus",
    "Chad",
    "Coke",
    "Colin",
    "Conan",
    "Corinne",
    "Cross",
    "Crystal",
    "Dallas",
    "Dandy",
    "Dang",
    "Deck",
    "Dell",
    "Diamond",
    "Diesis",
    "Dingo",
    "Disco",
    "Doha",
    "Dublino",
    "Duma",
    "Durian",
    "Emmy",
    "Melbourne",
    "Nizza",
    "Sidney",
    "Tenerife",
    "Tosca",
    "Valencia",
    "Vienna",
]

le_comfort_clients_list = [
    {
        "id": '2e4d3893-6114-4306-bec3-165fb7cc5ddd',
        "name": 'Mobilveneto'
    },
    {
        "id": '0ff3e969-a2d7-4d0f-bfb0-6899f0ccc8f7',
        "name": 'Fonte Del Mobile'
    },
    {
        "id": 'fedb5e77-56c9-4800-8929-269dfb016289',
        "name": 'Arredamenti Riuniti'
    },
    {
        "id": 'c1e431cd-ec2e-4549-93ce-d6e1f176564a',
        "name": 'Store Cadoneghe Rampazzo'
    },
    {
        "id": '7eb86182-adc8-41d5-ba23-82313407be09',
        "name": 'Arredo Ingross 3 Rampazzo'
    },
    {
        "id": 'f392f504-5fc1-477d-869f-4f798cb60e07',
        "name": 'Mobilificio Roncato'
    },
    {
        "id": 'e01b596c-8149-4e6b-873d-3928011e6c98',
        "name": 'Il Patio Arreda'
    },
]